### ISSUE TITLE
Add endpoint for lesson times

### ISSUE THREAD

**Issue by dominik-korsa** [Cloud11665/sabat.dev#5]
https://github.com/qepasa/VLO-Schedule/blob/a36ba5b464b2b3f251dae8dab2653da66651f652/src/components/timetable/timetableHeader/TimetableHeaderComponent.tsx#L11
Add API endpoint (for example `/api/tim`) returning start and end times of each lesson.

PS: I'm trying to integrate this API in my project: https://dominik-korsa.github.io/timetable-backpack-assistant/ :)

**Comment by dominik-korsa** [comment]
It could also be a good idea to separate the lesson number and lesson index, as they aren't necessarily the same

**Comment by Cloud11665** [comment]
What would the response look like ?

**Comment by qepasa** [comment]
@dominik-korsa thanks for bringing it out. I would appreciate such an endpoint as well.

As for the response. Edupage has a following format for this data:
```
 "data_rows": [
                    {
                        "id": "0",
                        "name": "0",
                        "short": "0",
                        "period": "0",
                        "starttime": "07:10",
                        "endtime": "07:55"
                    },
                    {
                        "id": "1",
                        "name": "1",
                        "short": "1",
                        "period": "1",
                        "starttime": "08:00",
                        "endtime": "08:45"
                    },
                    {
                        "id": "2",
                        "name": "2",
                        "short": "2",
                        "period": "2",
                        "starttime": "09:00",
                        "endtime": "09:45"
                    },
                  ...
                    {
                        "id": "10",
                        "name": "10",
                        "short": "10",
                        "period": "10",
                        "starttime": "16:30",
                        "endtime": "17:15"
                    }
                ],
```

I would suggest parsing this into array of objects:
```
{
    time_index: number,
    start_time: string,
    end_time: string
}
```
where start/end times are raw hours (like in edupage response).

What do you think @dominik-korsa @Cloud11665

**Comment by Cloud11665** [comment]
lgtm

**Comment by dominik-korsa** [comment]
I'd also suggest adding the `name` field (in my parser I just call it `number`)

**Comment by Cloud11665** [comment]
Wouldn't the `id` field of the object inside the list be pointless? Because `resp[i].id == i`.
Also, backend already deals with time anomalies in the edupage response.

**Comment by dominik-korsa** [comment]
If that's really the case, then the `name` field isn't needed indeed. Some schools however start the numbering with 1 (not sure if Edupage allows it)

**Comment by qepasa** [comment]
Yeah, I guess it makes sense. On the other hand, having **explicit** relationships/foreign key and consistent naming (between `time_index` here and in lesson) makes this API more understandable and/or self-documenting. You do not need to rely on order of data. Also, there are minuscule amount of data here so I wouldn't mind this kind of duplication. Idk if that's better, just my intuition.

I'm not sure if I understood you correctly @dominik-korsa but are you proposing renaming `time_index` to `name`? I would prefer to keep `time_index` in order to keep consistency with `lesson` object format. 

As for your point with numbering class slots starting with one - good point. Reinforces the need for `time_index`

**Comment by dominik-korsa** [comment]
I'm not suggesting renaming `time_index` but adding the `name` field from the edupage response in addition to `time_index`

**Comment by qepasa** [comment]
Ahh ok. Sure, I have no objections but once again it is for @Cloud11665  to decide (as he is the owner of this codebase). I guess some schools may name their course time-slots differently so it makes sense to increase versatility.

In short `name` from edupage response would stay as is and `period` would be mapped to `time_index`.

**Comment by qepasa** [comment]
Which field from edupage response is mapped to keys in these objects? I would suggest using the same capitalization (i.e. lowercase) as in other endpoints.

**Comment by Cloud11665** [comment]
ok, `/api/tim` endpoint is live now
